
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Time = 811.04F,
    Input_voltage = 3F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual El_power with predicted El_power from sample data...\n\n");


Console.WriteLine($"Time: {811.04F}");
Console.WriteLine($"Input_voltage: {3F}");
Console.WriteLine($"El_power: {1199.404F}");


// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);
Console.WriteLine($"\n\nPredicted El_power: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

